#!/bin/bash
    #SBATCH --partition general
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 1
#SBATCH --mem-per-cpu 8G
#SBATCH --time 2-6:00:00
#SBATCH --job-name jupyter-notebook
#SBATCH --output jupyter-notebook-%J.log

# Adjust your walltime above with the --time issue


# get tunneling info
XDG_RUNTIME_DIR=""
port=$(shuf -i8000-9999 -n1)
node=$(hostname -s)
user=$(whoami)
cluster=$(hostname -f | awk -F"." '{print $2}')

# print tunneling instructions ... jupyter-log
echo -e "
Paste into terminal command to create your ssh tunnel:
ssh -N -L ${port}:${node}:${port} ${user}@m3.massive.org.au
or if you have it    
autossh -N -L ${port}:${node}:${port} ${user}@m3.massive.org.au


Paste this URL into your local browser to access the jupyter notebook: 
localhost:${port}  (tou may need to prefix this with https:// if using password)
"

# Load modules or conda environments here
# TODO: you will have to adapt the following lines for your local environment
module load anaconda/5.1.0-Python3.6-gcc5
# this script adds conda to our PATH
. /usr/local/anaconda/5.1.0-Python3.6-gcc5/etc/profile.d/conda.sh
conda activate su62_scratch/volker_conda/myenv/

# start jupyter notebook
jupyter-notebook --no-browser --port=${port} --ip=${node}
